/**
 * Generate a reviewable RouterOS policy script from resolved domain evidence.
 * @param {Array<{domain: string, ips?: string[], ipv6?: string[]}>} resolved
 * @param {object} options
 * @returns {string}
 */
function safe(value) {
  return String(value || '').replace(/[^a-zA-Z0-9._:-]/g, '_');
}

function generateScript(resolved, options = {}) {
  const listName = safe(options.listName || 'blocked_sites');
  const addFirewallRule = options.addFirewallRule !== false;
  const addIPv6 = options.addIPv6 !== false;
  const domains = resolved.map(r => r.domain).join(', ');
  const generatedAt = new Date().toISOString();
  const marker = `MikroTik Blocker:${listName}`;
  const lines = [
    '# Generated by MikroTik Blocker',
    `# Generated: ${generatedAt}`,
    `# Domains: ${domains}`,
    `# Address list: ${listName}`,
    `# Marker: ${marker}`,
    '# REVIEW BEFORE APPLYING. Export/backup the router first.',
    '',
    '# Remove previous generated IPv4 entries',
    `/ip firewall address-list remove [find list=${listName} comment~"^${marker} "]`,
    '',
    '# IPv4: populate address list',
    '/ip firewall address-list',
  ];

  for (const { domain, ips = [] } of resolved) {
    for (const ip of ips) lines.push(`add list=${listName} address=${ip} comment="${marker} ${safe(domain)}"`);
  }

  if (addIPv6) {
    lines.push('', '# Remove previous generated IPv6 entries', `/ipv6 firewall address-list remove [find list=${listName} comment~"^${marker} "]`, '', '# IPv6: populate address list', '/ipv6 firewall address-list');
    for (const { domain, ipv6 = [] } of resolved) {
      for (const ip of ipv6) lines.push(`add list=${listName} address=${ip} comment="${marker} ${safe(domain)}"`);
    }
  }

  if (addFirewallRule) {
    lines.push('', '# IPv4 enforcement — review rule placement', '/ip firewall filter');
    lines.push(`:if ([:len [find chain=forward dst-address-list=${listName} action=drop comment="${marker}"]] = 0) do={`);
    lines.push(`  add chain=forward dst-address-list=${listName} action=drop comment="${marker}" place-before=0`);
    lines.push('}');
    if (addIPv6) {
      lines.push('', '# IPv6 enforcement — review rule placement', '/ipv6 firewall filter');
      lines.push(`:if ([:len [find chain=forward dst-address-list=${listName} action=drop comment="${marker}"]] = 0) do={`);
      lines.push(`  add chain=forward dst-address-list=${listName} action=drop comment="${marker}" place-before=0`);
      lines.push('}');
    }
  }

  lines.push('', '# Rollback (review before running):');
  lines.push(`/ip firewall address-list remove [find list=${listName} comment~"^${marker} "]`);
  if (addIPv6) lines.push(`/ipv6 firewall address-list remove [find list=${listName} comment~"^${marker} "]`);
  lines.push(`/ip firewall filter remove [find comment="${marker}"]`);
  if (addIPv6) lines.push(`/ipv6 firewall filter remove [find comment="${marker}"]`);
  return lines.join('\n');
}

module.exports = { generateScript };
