/**
 * Generate RouterOS (.rsc) script from domain->IP map
 * @param {Array<{domain: string, ips: string[]}>} resolved
 * @param {object} options
 * @param {string} options.listName  - address-list name (default: blocked_sites)
 * @param {boolean} options.addFirewallRule - whether to add forward drop rule
 * @returns {string} RouterOS script
 */
function generateScript(resolved, options = {}) {
  const listName = options.listName || 'blocked_sites';
  const addFirewallRule = options.addFirewallRule !== false;
  const domains = resolved.map(r => r.domain).join(', ');

  const lines = [
    `# Generated by MikroTik Blocker`,
    `# Date: ${new Date().toISOString()}`,
    `# Domains: ${domains}`,
    `# List: ${listName}`,
    '',
    '# Step 1: Remove existing entries for these domains (clean update)',
  ];

  // Remove old entries by comment (domain name)
  for (const { domain } of resolved) {
    lines.push(`/ip firewall address-list remove [find list=${listName} comment="${domain}"]`);
  }

  lines.push('');
  lines.push('# Step 2: Add resolved IPs to address list');
  lines.push('/ip firewall address-list');

  for (const { domain, ips } of resolved) {
    if (!ips.length) {
      lines.push(`# WARNING: No IPs resolved for ${domain}`);
      continue;
    }
    for (const ip of ips) {
      lines.push(`add list=${listName} address=${ip} comment="${domain}"`);
    }
  }

  if (addFirewallRule) {
    lines.push('');
    lines.push('# Step 3: Add firewall drop rule (only if not already present)');
    lines.push('/ip firewall filter');
    lines.push(
      `:if ([:len [find chain=forward dst-address-list=${listName} action=drop]] = 0) do={`
    );
    lines.push(
      `  add chain=forward dst-address-list=${listName} action=drop comment="Block ${listName}" place-before=0`
    );
    lines.push(`}`);
  }

  return lines.join('\n');
}

module.exports = { generateScript };
