'use strict';
const assert=require('assert');
const {createSnapshot,validateSnapshot,snapshotFingerprint}=require('./routeros-snapshot');
const model={fingerprint:'actual-fp',routeros:{version:'7.21.4',major:7},source:{name:'fixture.rsc'},resources:[{kind:'firewall.filter',path:'/ip/firewall/filter',identity:'firewall.filter:comment=x',attributes:{comment:'x',password:'hidden'},status:'recognized'}],diagnostics:[]};
const a=createSnapshot(model,{captured_at:'2026-01-01T00:00:00Z'});
const b=createSnapshot(model,{captured_at:'2026-09-18T00:00:00Z'});
assert.strictEqual(a.snapshot.content_fingerprint,b.snapshot.content_fingerprint);
assert.strictEqual(a.snapshot.id,b.snapshot.id);
assert.strictEqual(snapshotFingerprint(a),a.snapshot.content_fingerprint);
assert.strictEqual(a.resources[0].attributes.password,'[REDACTED]');
assert.strictEqual(validateSnapshot(a,{actual_fingerprint:'actual-fp',routeros_major:7}).valid,true);
const corrupted=JSON.parse(JSON.stringify(a));corrupted.resources[0].attributes.comment='tampered';
assert.strictEqual(validateSnapshot(corrupted).valid,false);
const mismatch=validateSnapshot(a,{actual_fingerprint:'other'});assert.strictEqual(mismatch.valid,false);
const version=validateSnapshot(a,{routeros_major:6});assert.strictEqual(version.valid,false);
const malformed=validateSnapshot({schema_version:'1.0.0'});assert.strictEqual(malformed.valid,false);
assert.strictEqual(Object.isFrozen(a),true);assert.strictEqual(Object.isFrozen(a.snapshot),true);
const different=createSnapshot({...model,resources:[{...model.resources[0],attributes:{comment:'different'}}]});assert.notStrictEqual(a.snapshot.content_fingerprint,different.snapshot.content_fingerprint);
console.log('routeros-snapshot.test.js: all tests passed');