// Vercel Serverless Function — POST /api/resolve
const dns = require('dns');
const { Resolver } = dns.promises;

const DNS_SERVERS = (process.env.DNS_SERVERS || '8.8.8.8,1.1.1.1')
  .split(',')
  .map(s => s.trim());

async function resolveDomain(domain) {
  const clean = domain
    .replace(/^https?:\/\//i, '')
    .replace(/\/.*$/, '')
    .trim()
    .toLowerCase();

  const errors = [];
  for (const server of DNS_SERVERS) {
    try {
      const resolver = new Resolver();
      resolver.setServers([server]);
      const addresses = await resolver.resolve4(clean);
      return { domain: clean, ips: [...new Set(addresses)], error: null };
    } catch (err) {
      errors.push(`${server}: ${err.message}`);
    }
  }
  return { domain: clean, ips: [], error: errors.join(' | ') };
}

function generateScript(resolved, options = {}) {
  const listName = options.listName || 'blocked_sites';
  const addFirewallRule = options.addFirewallRule !== false;
  const domains = resolved.map(r => r.domain).join(', ');

  const lines = [
    `# Generated by MikroTik Blocker`,
    `# Date: ${new Date().toISOString()}`,
    `# Domains: ${domains}`,
    `# List: ${listName}`,
    '',
    '# Step 1: Remove existing entries for these domains (clean update)',
  ];

  for (const { domain } of resolved) {
    lines.push(`/ip firewall address-list remove [find list=${listName} comment="${domain}"]`);
  }

  lines.push('');
  lines.push('# Step 2: Add resolved IPs to address list');
  lines.push('/ip firewall address-list');

  for (const { domain, ips } of resolved) {
    if (!ips.length) {
      lines.push(`# WARNING: No IPs resolved for ${domain}`);
      continue;
    }
    for (const ip of ips) {
      lines.push(`add list=${listName} address=${ip} comment="${domain}"`);
    }
  }

  if (addFirewallRule) {
    lines.push('');
    lines.push('# Step 3: Add firewall drop rule (idempotent)');
    lines.push('/ip firewall filter');
    lines.push(`:if ([:len [find chain=forward dst-address-list=${listName} action=drop]] = 0) do={`);
    lines.push(`  add chain=forward dst-address-list=${listName} action=drop comment="Block ${listName}" place-before=0`);
    lines.push(`}`);
  }

  return lines.join('\n');
}

module.exports = async function handler(req, res) {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { domains, listName, addFirewallRule } = req.body || {};

  if (!domains || !Array.isArray(domains) || domains.length === 0) {
    return res.status(400).json({ error: 'domains array is required' });
  }

  const cleanDomains = domains
    .map(d => d.replace(/^https?:\/\//i, '').replace(/\/.*$/, '').trim().toLowerCase())
    .filter(d => d && /^[a-z0-9][a-z0-9.-]+\.[a-z]{2,}$/.test(d));

  if (cleanDomains.length === 0) {
    return res.status(400).json({ error: 'No valid domains provided' });
  }

  try {
    const results = await Promise.allSettled(cleanDomains.map(resolveDomain));
    const resolved = results.map(r =>
      r.status === 'fulfilled' ? r.value : { domain: '', ips: [], error: r.reason?.message }
    );
    const script = generateScript(resolved, { listName, addFirewallRule });
    return res.status(200).json({ resolved, script });
  } catch (err) {
    return res.status(500).json({ error: 'Resolution failed', detail: err.message });
  }
};
